# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c7b32375a61ae37754796b9bf35932e6ea2c0682803b7b9b853f7a1e2af936009edaff62efb7d17a910937b888a042da1b3244e65513d7af07c55d9d6726e7e

test:
  secret_key_base: c189c3a0aecd92c9ea897e510396abddac44c8e32fd8dc1e6606185b4b921e7b645b5b82d8785d4ab11be24140536e9e6955f065b224cf247bd3d7241e225119

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
